"""fix models

Revision ID: 0bc7ec9c9770
Revises: 3069ce165f23
Create Date: 2026-04-07 09:26:48.849190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc7ec9c9770'
down_revision: Union[str, Sequence[str], None] = '3069ce165f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_track_courses_career_track_id'), table_name='career_track_courses')
    op.drop_index(op.f('ix_career_track_courses_course_id'), table_name='career_track_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_career_track_courses_course_id'), 'career_track_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_career_track_courses_career_track_id'), 'career_track_courses', ['career_track_id'], unique=False)
    # ### end Alembic commands ###
