"""minor changes in models

Revision ID: c4a5b157f71b
Revises: 9951e844341b
Create Date: 2026-03-24 15:25:24.432011

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a5b157f71b'
down_revision: Union[str, Sequence[str], None] = '9951e844341b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    course_type = postgresql.ENUM('REQUIRED', 'ELECTIVE', name='coursetype')
    course_type.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'courses',
        sa.Column(
            'type', sa.Enum('REQUIRED', 'ELECTIVE', name='coursetype'), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'type')
    # ### end Alembic commands ###
    course_type = postgresql.ENUM('REQUIRED', 'ELECTIVE', name='coursetype')
    course_type.drop(op.get_bind())
