"""duplication

Revision ID: d5d7104854d6
Revises: 0bc7ec9c9770
Create Date: 2026-04-13 08:49:07.829044

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d7104854d6'
down_revision: Union[str, Sequence[str], None] = '0bc7ec9c9770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'career_tracks', 'title', existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        'career_tracks',
        'description',
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_career_tracks_title'), table_name='career_tracks')
    op.drop_index(op.f('ix_career_tracks_user_id'), table_name='career_tracks')
    op.drop_index(op.f('ix_prerequisites_course_id'), table_name='prerequisites')
    op.drop_index(
        op.f('ix_prerequisites_prerequisite_course_id'), table_name='prerequisites'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_prerequisites_prerequisite_course_id'),
        'prerequisites',
        ['prerequisite_course_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_prerequisites_course_id'), 'prerequisites', ['course_id'], unique=False
    )
    op.create_index(
        op.f('ix_career_tracks_user_id'), 'career_tracks', ['user_id'], unique=False
    )
    op.create_index(
        op.f('ix_career_tracks_title'), 'career_tracks', ['title'], unique=True
    )
    op.alter_column(
        'career_tracks',
        'description',
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        'career_tracks', 'title', existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
