name: Deploy Dev (Simple)

on:
  push:
    branches:
      - ci-cd
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}
      VM_PORT: ${{ secrets.VM_PORT }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}

      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      IMAGE_TAG: dev-latest

      DB__USER: ${{ secrets.DB__USER }}
      DB__PASSWORD: ${{ secrets.DB__PASSWORD }}
      DB__NAME: "edumap_dev"
      AUTH__JWT_SECRET_KEY: ${{ secrets.AUTH__JWT_SECRET_KEY }}
      RBAC__ADMIN_EMAIL: ${{ secrets.RBAC__ADMIN_EMAIL }}
      RBAC__ADMIN_PASSWORD: ${{ secrets.RBAC__ADMIN_PASSWORD }}

      NPM_DB_PASSWORD: ${{ secrets.NPM_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and push image
        uses: ./.github/actions/ansible-runner
        with:
          playbook: build_and_push.yml

      - name: Deploy compose stack
        uses: ./.github/actions/ansible-runner
        with:
          playbook: deploy_compose.yml